theme: jekyll-theme-cayman
title: Josh's website
  description: My Blog
author: Josh Lau
defaults:
  - scope:
      path: "*.html"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
